name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix: 
        file: ['examples/optifine-1.zip']
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CurseForge: ${{ secrets.CURSEFORGE }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Download mods
        run: dotnet run --project src/m_mods.csproj -- "${{ matrix.file }}" out
      - name: Archive mods
        run: cd out && zip -9 -r ../mods.zip ./*
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "modpack.zip,mods.zip"
          bodyFile: "out/README.md"
